# Generated by Django 5.2.7 on 2025-10-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_is_best_seller_book_is_bestseller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='book',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
